### ISSUE TITLE
Give visual feedback when a correct or wrong answer is provided 

### ISSUE THREAD

**Issue by chowder** [chowder/glypoon#1]

**Comment by 0xSk3ttch** [comment]
I can help. This seems like a fun project. Using Tailwind?

**Comment by chowder** [comment]
No strong preference! Vanilla CSS would be ok too.

**Comment by 0xSk3ttch** [comment]
Trackin! I saw Tailwind as a dependency, so I wasn't sure

**Comment by jacobbundren** [comment]
Hey @chowder, I'm getting a 403 when trying to push. Is this set up to take contributions?
