### ISSUE TITLE
Create an API to fetch the letters and answers 

### ISSUE THREAD

**Issue by chowder** [chowder/glypoon#2]

**Comment by ting-c** [comment]
Hi, I would love to contribute to this fun project. This [API](https://www.datamuse.com/api/) looks like a good fit for the purpose you've described.

**Comment by chowder** [comment]
Hi @ting-c , thanks for the suggestion.

For now this is generated daily through a GH action, which commits a puzzle file bundled with the build. 

see: https://github.com/chowder/glypoon/blob/main/.github/workflows/make_puzzle.yml
